_target_: rgbd_dataset.rgbd_dataset.datasets.SemiStaticSim.SemiStaticSim
dataset_name: "semistaticsim"
base_path: ${data_dir}
scene: ???
width: 640
height: 640
resized_width: -1
resized_height: -1
sequence_start: 0
sequence_end: -1
sequence_stride: 1
relative_pose: false
depth_scale: 1000.0
fx: 320.0
fy: 320.0
cx: 320.0
cy: 320.0
point_cloud: false
depth_trunc: 5.0
img_dir: images
rgb_dir: rgb_first_view
depth_dir: depth
semantics_dir: semantics
pose_dir: poses
cam_offset: 0.675 # Dataset dependant
