_target_: concept_graphs.inference.MapQueryEngine.QueryObjectsGT
map_path: ${map_path}
perpetua_estimators_path: ${perpetua_estimators_path}
perpetua_map_path: ${perpetua_map_path}
perpetua_map_full_overwrite: ${perpetua_map_full_overwrite}
ft_extractor: ???
semantic_sim_metric: ???
verifier: ???
receptacles_bbox: ???
top_k: ${top_k}
device: ${device}
pickupable_bbox: ???
pickupable_existence: ???
